[pytest]
addopts = --slowmo=200 --alluredir=allure-results
testpaths = tests

markers =
    sanity: Basic functionality tests
    regression: Full regression suite
    smoke: Quick build verification
    critical: Critical business flows